### ISSUE TITLE
Escrow Account Management 

### ISSUE THREAD

**Issue by sangier** [cosmos/solidity-ibc-eureka#6]
- [ ] Research how to manage escrow account 
- [ ] Implement escrow account management. 

 - Serdar comment: Right now, we don't have an escrow, but the app should work good enough for testing.

**Comment by srdtrk** [comment]
We might want to go in the direction of [yui-ibc-solidity](https://github.com/hyperledger-labs/yui-ibc-solidity) and introduce an escrow contract (similar to bank keeper). Thanks for this suggestion @gjermundgaraba. This would help with:

1. **Migration**: Right now, all escrow tokens are held by `ICS20Transfer.sol`. Since we plan to introduce migrations via proxy contracts in #12, it would make more sense for there to be a separate escrow manager contract that manages the escrow. This way, we can migrate ICS20 without moving the escrowed funds.

2. **Modularity**: Right now, `ICS20Transfer.sol` handles the conversions between ERC20 and SdkCoin via the `SdkCoin.sol` library. This is not ideal since this `ICS20Transfer.sol` implementation would only be usable between ERC20 and Cosmos. It might make more sense to move this layer to the escrow contract. But this still needs more research.
